### ISSUE TITLE
Table missing additional methods

### ISSUE THREAD

**Issue by craigwelch** [learn-co-students/selecting-single-elements-readme-bootcamp-prep-000#1]
In the section "OTHER CSS SELECTORS" the second table is identical to the first when is seems that it should include additional methods. 

i.e. "We can also select elements using other methods. Let's add in those other methods to our chart.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
