### ISSUE TITLE
No link to "Charles Babbage" in the gray box

### ISSUE THREAD

**Issue by bentonwong** [learn-co-students/selecting-single-elements-readme-bootcamp-prep-000#5]
The link to Charles Babbage only resides in the text body.  It should be changed to "London, England" after the proper href anchor tags are added.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
