### ISSUE TITLE
Retrieving Attributes example gives an error. 

### ISSUE THREAD

**Issue by writer1200sea** [learn-co-students/selecting-single-elements-readme-bootcamp-prep-000#7]
I tried copying the instructions into the console as directed in the text and got this error:

let londonAnchor = document.querySelector('.birthplace').querySelector('a')
londonAnchor.constructor
VM248:2 Uncaught TypeError: Cannot read property 'constructor' of null
    at <anonymous>:2:14

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
